from PyQt6 import QtWidgets


class PageCreateNoteInit(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("page_create_note")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_create_note_name = QtWidgets.QFrame(self)
        self.frame_create_note_name.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_create_note_name.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_create_note_name.setObjectName("frame_create_note_name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_create_note_name)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_create_note_name = QtWidgets.QLineEdit(self.frame_create_note_name)
        self.lineEdit_create_note_name.setObjectName("lineEdit_create_note_name")
        self.horizontalLayout.addWidget(self.lineEdit_create_note_name)
        self.verticalLayout_5.addWidget(self.frame_create_note_name)
        self.frame_create_note_text = QtWidgets.QFrame(self)
        self.frame_create_note_text.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_create_note_text.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_create_note_text.setObjectName("frame_create_note_text")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_create_note_text)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_create_note_text = QtWidgets.QTextEdit(self.frame_create_note_text)
        self.textEdit_create_note_text.setObjectName("textEdit_create_note_text")
        self.horizontalLayout_2.addWidget(self.textEdit_create_note_text)
        self.verticalLayout_5.addWidget(self.frame_create_note_text)
        self.frame_create_note_notification = QtWidgets.QFrame(self)
        self.frame_create_note_notification.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_create_note_notification.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_create_note_notification.setObjectName("frame_create_note_notification")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_create_note_notification)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_create_note_notification_activate = QtWidgets.QCheckBox(self.frame_create_note_notification)
        self.checkBox_create_note_notification_activate.setObjectName("checkBox_create_note_notification_activate")
        self.horizontalLayout_3.addWidget(self.checkBox_create_note_notification_activate)
        self.dateTimeEdit_create_note = QtWidgets.QDateTimeEdit(self.frame_create_note_notification)
        self.dateTimeEdit_create_note.setObjectName("dateTimeEdit_create_note")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_create_note)
        self.verticalLayout_5.addWidget(self.frame_create_note_notification)
        self.frame_create_note_navigate = QtWidgets.QFrame(self)
        self.frame_create_note_navigate.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_create_note_navigate.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_create_note_navigate.setObjectName("frame_create_note_navigate")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_create_note_navigate)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_create_note_save = QtWidgets.QPushButton(self.frame_create_note_navigate)
        self.pushButton_create_note_save.setObjectName("pushButton_create_note_save")
        self.horizontalLayout_4.addWidget(self.pushButton_create_note_save)
        self.pushButton_create_note_cancel = QtWidgets.QPushButton(self.frame_create_note_navigate)
        self.pushButton_create_note_cancel.setObjectName("pushButton_create_note_cancel")
        self.horizontalLayout_4.addWidget(self.pushButton_create_note_cancel)
        self.verticalLayout_5.addWidget(self.frame_create_note_navigate)


def get_widget():
    return PageCreateNoteInit()


def get_name():
    return "Note"
